"""Initial database schema

Revision ID: 5939146ec8fa
Revises: 
Create Date: 2025-06-09 00:19:27.948081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5939146ec8fa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index('ix_event_created', 'audit_logs', ['event_type', 'created_at'], unique=False)
    op.create_index('ix_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_table('invoice_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('stripe_id', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('document_content', sa.Text(), nullable=True),
    sa.Column('document_url', sa.String(length=500), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_id', 'document_type', 'provider', name='uix_invoice_doc_provider')
    )
    op.create_index(op.f('ix_invoice_documents_id'), 'invoice_documents', ['id'], unique=False)
    op.create_index(op.f('ix_invoice_documents_invoice_id'), 'invoice_documents', ['invoice_id'], unique=False)
    op.create_index('ix_invoice_type', 'invoice_documents', ['invoice_id', 'document_type'], unique=False)
    op.create_table('processed_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stripe_id', sa.String(length=255), nullable=False),
    sa.Column('invoice_type', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_invoice_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.String(length=255), nullable=True),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('customer_tax_id', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('invoice_date', sa.DateTime(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_id', 'provider', name='uix_stripe_provider')
    )
    op.create_index('ix_customer_id', 'processed_invoices', ['customer_id'], unique=False)
    op.create_index(op.f('ix_processed_invoices_id'), 'processed_invoices', ['id'], unique=False)
    op.create_index(op.f('ix_processed_invoices_stripe_id'), 'processed_invoices', ['stripe_id'], unique=False)
    op.create_index('ix_provider_status', 'processed_invoices', ['provider', 'status'], unique=False)
    op.create_index('ix_status_created', 'processed_invoices', ['status', 'created_at'], unique=False)
    op.create_table('processing_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('stripe_id', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('request_data', sa.JSON(), nullable=True),
    sa.Column('response_data', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('initiated_by', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_invoice_created', 'processing_history', ['invoice_id', 'started_at'], unique=False)
    op.create_index(op.f('ix_processing_history_id'), 'processing_history', ['id'], unique=False)
    op.create_index(op.f('ix_processing_history_invoice_id'), 'processing_history', ['invoice_id'], unique=False)
    op.create_index('ix_stripe_id_history', 'processing_history', ['stripe_id'], unique=False)
    op.create_table('provider_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('config_data', sa.JSON(), nullable=False),
    sa.Column('rate_limit', sa.Integer(), nullable=True),
    sa.Column('rate_window', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider')
    )
    op.create_index('ix_provider_active', 'provider_configs', ['provider', 'active'], unique=False)
    op.create_index(op.f('ix_provider_configs_id'), 'provider_configs', ['id'], unique=False)
    op.create_table('retry_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('stripe_id', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('retry_after', sa.DateTime(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_active_retry', 'retry_queue', ['active', 'retry_after'], unique=False)
    op.create_index('ix_invoice_active', 'retry_queue', ['invoice_id', 'active'], unique=False)
    op.create_index(op.f('ix_retry_queue_active'), 'retry_queue', ['active'], unique=False)
    op.create_index(op.f('ix_retry_queue_id'), 'retry_queue', ['id'], unique=False)
    op.create_index(op.f('ix_retry_queue_invoice_id'), 'retry_queue', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_retry_queue_retry_after'), 'retry_queue', ['retry_after'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_retry_queue_retry_after'), table_name='retry_queue')
    op.drop_index(op.f('ix_retry_queue_invoice_id'), table_name='retry_queue')
    op.drop_index(op.f('ix_retry_queue_id'), table_name='retry_queue')
    op.drop_index(op.f('ix_retry_queue_active'), table_name='retry_queue')
    op.drop_index('ix_invoice_active', table_name='retry_queue')
    op.drop_index('ix_active_retry', table_name='retry_queue')
    op.drop_table('retry_queue')
    op.drop_index(op.f('ix_provider_configs_id'), table_name='provider_configs')
    op.drop_index('ix_provider_active', table_name='provider_configs')
    op.drop_table('provider_configs')
    op.drop_index('ix_stripe_id_history', table_name='processing_history')
    op.drop_index(op.f('ix_processing_history_invoice_id'), table_name='processing_history')
    op.drop_index(op.f('ix_processing_history_id'), table_name='processing_history')
    op.drop_index('ix_invoice_created', table_name='processing_history')
    op.drop_table('processing_history')
    op.drop_index('ix_status_created', table_name='processed_invoices')
    op.drop_index('ix_provider_status', table_name='processed_invoices')
    op.drop_index(op.f('ix_processed_invoices_stripe_id'), table_name='processed_invoices')
    op.drop_index(op.f('ix_processed_invoices_id'), table_name='processed_invoices')
    op.drop_index('ix_customer_id', table_name='processed_invoices')
    op.drop_table('processed_invoices')
    op.drop_index('ix_invoice_type', table_name='invoice_documents')
    op.drop_index(op.f('ix_invoice_documents_invoice_id'), table_name='invoice_documents')
    op.drop_index(op.f('ix_invoice_documents_id'), table_name='invoice_documents')
    op.drop_table('invoice_documents')
    op.drop_index('ix_resource', table_name='audit_logs')
    op.drop_index('ix_event_created', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
